//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "loan_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub payment_id: i32,
    pub loan_id: i32,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub principal_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub interest_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub total_amount: Decimal,
    pub payment_date: Date,
    pub payment_mode: Option<String>,
    pub reference_number: Option<String>,
    pub txn_group_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::loans::Entity",
        from = "Column::LoanId",
        to = "super::loans::Column::LoanId",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Loans,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::loans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loans.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
