//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

use super::sea_orm_active_enums::LoanStatus;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "loans")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub loan_id: i32,
    #[sea_orm(column_type = "String(StringLen::N(100))")]
    pub lender_name: String,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub principal_amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub interest_rate: Option<Decimal>,
    pub loan_date: Date,
    pub due_date: Option<Date>,
    #[sea_orm(column_type = "Decimal(Some((18, 2)))")]
    pub outstanding_balance: Decimal,
    pub status: LoanStatus,
    pub txn_group_id: Option<Uuid>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub created_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::loan_payments::Entity")]
    LoanPayments,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::loan_payments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoanPayments.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
