//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "metric_snapshots")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "String(StringLen::N(8))")]
    pub period_type: String,
    #[sea_orm(column_type = "String(StringLen::N(10))")]
    pub period_key: String,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub metric_key: String,
    #[sea_orm(column_type = "Decimal(Some((18, 4)))")]
    pub value: Decimal,
    pub computed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
