//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::sea_orm_active_enums::PaymentType;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "purchases")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub purchase_id: i32,
    pub item_code: String,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub cost_per_unit: Decimal,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub total_cost: Option<Decimal>,
    pub quantity: Decimal,
    pub purchase_date: Date,
    pub supplier_id: i32,
    pub payment_type: Option<PaymentType>,
    pub created_by: Option<i32>,
    pub purchase_order_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,

    #[sea_orm(
        belongs_to = "super::items::Entity",
        from = "Column::ItemCode",
        to = "super::items::Column::ItemCode",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Items,

    // CHANGED: Updated mapping for Supplier ID
    #[sea_orm(
        belongs_to = "super::suppliers::Entity",
        from = "Column::SupplierId",        // New column in 'purchases'
        to = "super::suppliers::Column::SupplierId", // Primary key in 'suppliers'
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Suppliers,

    #[sea_orm(
        belongs_to = "super::purchase_orders::Entity",
        from = "Column::PurchaseOrderId",
        to = "super::purchase_orders::Column::PurchaseOrderId",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    PurchaseOrders,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Items.def()
    }
}

impl Related<super::suppliers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Suppliers.def()
    }
}

impl Related<super::purchase_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurchaseOrders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
