//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

use super::sea_orm_active_enums::PaymentType;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "purchase_orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub purchase_order_id: i32,
    pub supplier_id: i32,
    pub purchase_date: Date,
    pub payment_type: Option<PaymentType>,
    pub created_by: i32,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub total_cost: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::suppliers::Entity",
        from = "Column::SupplierId",
        to = "super::suppliers::Column::SupplierId",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Suppliers,

    #[sea_orm(
        has_many = "super::purchases::Entity",
        from = "Column::PurchaseOrderId",
        to = "super::purchases::Column::PurchaseOrderId"
    )]
    Purchases,
}

impl Related<super::suppliers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Suppliers.def()
    }
}

impl Related<super::purchases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Purchases.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
