//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use std::fmt;

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "batch_status")]
pub enum BatchStatus {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "closed")]
    Closed,
    #[sea_orm(string_value = "live")]
    Live,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "purchase_category")]
pub enum PurchaseCategory {
    #[sea_orm(string_value = "bird")]
    Bird,
    #[sea_orm(string_value = "feed")]
    Feed,
    #[sea_orm(string_value = "medicine")]
    Medicine,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "requirement_category"
)]
pub enum RequirementCategory {
    #[sea_orm(string_value = "bird")]
    Bird,
    #[sea_orm(string_value = "feed")]
    Feed,
    #[sea_orm(string_value = "medicine")]
    Medicine,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "supplier_type")]
pub enum SupplierType {
    #[sea_orm(string_value = "feed")]
    Feed,
    #[sea_orm(string_value = "chick")]
    Chick,
    #[sea_orm(string_value = "medicine")]
    Medicine,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Hash)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_role")]
pub enum UserRole {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "supervisor")]
    Supervisor,
    #[sea_orm(string_value = "accountant")]
    Accountant,
    #[sea_orm(string_value = "trader")]
    Trader,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "requirement_status")]
pub enum RequirementStatus {
    #[sea_orm(string_value = "accept")]
    Accept,
    #[sea_orm(string_value = "decline")]
    Decline,
    #[sea_orm(string_value = "pending")]
    Pending,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "movement_type")]
pub enum MovementType {
    #[sea_orm(string_value = "purchase")]
    Purchase,
    #[sea_orm(string_value = "allocation")]
    Allocation,
    #[sea_orm(string_value = "adjustment")]
    Adjustment,
    #[sea_orm(string_value = "transfer")]
    Transfer,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "ledger_account_type"
)]
pub enum LedgerAccountType {
    #[sea_orm(string_value = "asset")]
    Asset,
    #[sea_orm(string_value = "liability")]
    Liability,
    #[sea_orm(string_value = "equity")]
    Equity,
    #[sea_orm(string_value = "revenue")]
    Revenue,
    #[sea_orm(string_value = "expense")]
    Expense,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "item_category")]
pub enum ItemCategory {
    #[sea_orm(string_value = "feed")]
    Feed,
    #[sea_orm(string_value = "medicine")]
    Medicine,
    #[sea_orm(string_value = "chicks")]
    Chicks,
    #[sea_orm(string_value = "finished_birds")]
    FinishedBirds,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "loan_status")]
pub enum LoanStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "closed")]
    Closed,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "payment_type")]
pub enum PaymentType {
    #[sea_orm(string_value = "CASH")]
    Cash,
    #[sea_orm(string_value = "PAYABLE")]
    Payable,
    #[sea_orm(string_value = "RECEIVABLE")]
    Receivable,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "other_expense_category"
)]
pub enum OtherExpenseCategory {
    #[sea_orm(string_value = "feed_transfer")]
    FeedTransfer,
    #[sea_orm(string_value = "loading_unloading")]
    LoadingUnloading,
    #[sea_orm(string_value = "petrol")]
    Petrol,
    #[sea_orm(string_value = "employee_expenses")]
    EmployeeExpenses,
    #[sea_orm(string_value = "misc")]
    Misc,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_status")]
pub enum OrderStatus {
    #[sea_orm(string_value = "PENDING")]
    Pending,
    #[sea_orm(string_value = "WEIGHT_ENTERED")]
    WeightEntered,
    #[sea_orm(string_value = "CONFIRMED")]
    Confirmed,
    #[sea_orm(string_value = "CANCELLED_BY_TRADER")]
    CancelledByTrader,
    #[sea_orm(string_value = "REJECTED_BY_SUPERVISOR")]
    RejectedBySupervisor,
    #[sea_orm(string_value = "EXPIRED")]
    Expired,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ledger_entry_type")]
pub enum LedgerEntryType {
    #[sea_orm(string_value = "debit")]
    Debit,
    #[sea_orm(string_value = "payment")]
    Payment,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "payment_mode")]
pub enum PaymentMode {
    #[sea_orm(string_value = "cash")]
    Cash,
    #[sea_orm(string_value = "bank")]
    Bank,
}

impl fmt::Display for ItemCategory {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            ItemCategory::Feed => write!(f, "feed"),
            ItemCategory::Medicine => write!(f, "medicine"),
            ItemCategory::Chicks => write!(f, "chicks"),
            ItemCategory::FinishedBirds => write!(f, "finished_birds"),
        }
    }
}
