//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "stock_returns")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub return_id: i32,

    pub allocation_line_id: i32,

    #[sea_orm(indexed)]
    pub batch_id: i32,

    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub return_qty: Decimal,

    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub unit_cost: Decimal,

    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub return_value: Decimal,

    pub return_date: Date,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::batch_allocation_lines::Entity",
        from = "Column::AllocationLineId",
        to = "super::batch_allocation_lines::Column::AllocationLineId",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    BatchAllocationLines,

    #[sea_orm(
        belongs_to = "super::batches::Entity",
        from = "Column::BatchId",
        to = "super::batches::Column::BatchId",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Batches,
}

impl Related<super::batch_allocation_lines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BatchAllocationLines.def()
    }
}

impl Related<super::batches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Batches.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
